### ISSUE TITLE
pair hmm driver

### ISSUE THREAD

**Issue by ramcn** [Intel-HLS/BIGstack#4]
Hello,

I am trying to setup this on one of our test system with intel fpga and able to install and set up most of the stack using the wiki instructions.

However, I am not able to find the information where I can download the pair hmm driver intel-fpga-pairhmm-pac_a10-1.1.3-1.x86_64.rpm. Please let me know where I can download this driver.

Thank you,
Ram

**Comment by mepowers** [comment]
Hi Ram,

We can help with this.  Let me confirm I have the latest driver, and then I'll share with you.

Best,
Marissa

**Comment by ramcn** [comment]
Hi Marissa,

Did you get a chance to confirm about the latest driver? Please let me know when it will available to share.

Thank you,
Ram

**Comment by daizao** [comment]
Hi Marissa,
Did you confirm about the latest driver ? Please let me know where it could be download.
Thank you !
Dai zao

**Comment by mepowers** [comment]
@daizao @ramcn - unfortunately we no longer support or distribute this driver.  Falcon has a GATK pipeline on Arria10 and Stratix10 FPGAs:  https://www.falconcomputing.com/falcon-life-science-solutions/

**Comment by daizao** [comment]
@mepowers
ok, thank you very much!
